export const songGameFiles = [
  {
    letter: 'A',
    firstObjectName: 'Abelha',
    secondObjectName: 'Aranha',
    thirdObjectName: 'Aviao',
  },
  {
    letter: 'B',
    firstObjectName: 'Boneca',
    secondObjectName: 'Bola',
    thirdObjectName: 'Banana',
  },
  {
    letter: 'C',
    firstObjectName: 'Casa',
    secondObjectName: 'Carro',
    thirdObjectName: 'Cachorro',
  },
  {
    letter: 'D',
    firstObjectName: 'Dinossauro',
    secondObjectName: 'Duende',
    thirdObjectName: 'Dado',
  },
  {
    letter: 'E',
    firstObjectName: 'Elefante',
    secondObjectName: 'Estrela',
    thirdObjectName: 'Escova',
  },
  {
    letter: 'F',
    firstObjectName: 'Foca',
    secondObjectName: 'Fada',
    thirdObjectName: 'Flor',
  },
  {
    letter: 'G',
    firstObjectName: 'Gato',
    secondObjectName: 'Galinha',
    thirdObjectName: 'Girafa',
  },
  {
    letter: 'H',
    firstObjectName: 'Helicoptero',
    secondObjectName: 'Hospital',
    thirdObjectName: 'Hipopotamo',
  },
  {
    letter: 'I',
    firstObjectName: 'Iguana',
    secondObjectName: 'Indio',
    thirdObjectName: 'Igreja',
  },
  {
    letter: 'J',
    firstObjectName: 'Jacare',
    secondObjectName: 'Joaninha',
    thirdObjectName: 'Jornal',
  },
  {
    letter: 'K',
    firstObjectName: 'Kilo',
    secondObjectName: 'Kiwi',
    thirdObjectName: 'Karate',
  },
  {
    letter: 'L',
    firstObjectName: 'Leao',
    secondObjectName: 'Laranja',
    thirdObjectName: 'Livro',
  },
  {
    letter: 'M',
    firstObjectName: 'Macaco',
    secondObjectName: 'Minhoca',
    thirdObjectName: 'Maca',
  },
  {
    letter: 'N',
    firstObjectName: 'Navio',
    secondObjectName: 'Ninho',
    thirdObjectName: 'Noz',
  },
  {
    letter: 'O',
    firstObjectName: 'Ovo',
    secondObjectName: 'Ovelha',
    thirdObjectName: 'Olho',
  },
  {
    letter: 'P',
    firstObjectName: 'Pato',
    secondObjectName: 'Peixe',
    thirdObjectName: 'Porco',
  },
  {
    letter: 'Q',
    firstObjectName: 'Quati',
    secondObjectName: 'Queijo',
    thirdObjectName: 'Quebracabeca',
  },
  {
    letter: 'R',
    firstObjectName: 'Rato',
    secondObjectName: 'Rinoceronte',
    thirdObjectName: 'Robo',
  },
  {
    letter: 'S',
    firstObjectName: 'Sapo',
    secondObjectName: 'Sino',
    thirdObjectName: 'Sorvete',
  },
  {
    letter: 'T',
    firstObjectName: 'Tubarao',
    secondObjectName: 'Trem',
    thirdObjectName: 'Tartaruga',
  },
  {
    letter: 'U',
    firstObjectName: 'Uva',
    secondObjectName: 'Unicornio',
    thirdObjectName: 'Urso',
  },
  {
    letter: 'V',
    firstObjectName: 'Vaca',
    secondObjectName: 'Violao',
    thirdObjectName: 'Vaso',
  },
  {
    letter: 'W',
    firstObjectName: 'Wafer',
    secondObjectName: 'Windsurf',
    thirdObjectName: 'Wifi',
  },
  {
    letter: 'X',
    firstObjectName: 'Xicara',
    secondObjectName: 'Xadrez',
    thirdObjectName: 'Xarope',
  },
  {
    letter: 'Y',
    firstObjectName: 'Yogurte',
    secondObjectName: 'Yoga',
    thirdObjectName: 'Yakisoba',
  },
  {
    letter: 'Z',
    firstObjectName: 'Zebra',
    secondObjectName: 'Zoologico',
    thirdObjectName: 'Zangao',
  },
];
